name = "DiferenciasFinitas"
uuid = "212e24a8-3754-40cb-813a-99bae54620bc"
authors = ["delficomerso "]
version = "0.1.0"

[deps]
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
LaTeXStrings = "1.4.0"
LinearAlgebra = "1.11.0"
Plots = "1.40.19"
Revise = "3.9.0"
